FROM ubuntu:18.04
RUN apt-get update -y
#RUN apt-get install -y python-pip python-dev build-essential
RUN apt-get install -y python3.6 python3-pip
COPY . /app
WORKDIR /app
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
RUN pip3 install pipenv
RUN pipenv install

CMD ["python3", "aristoptimiser/web_optimiser_configuration.py"]
